import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/features/navigation/Navbar";

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased flex flex-col min-h-screen`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
